name: agileflight
channels:
  - conda-forge
  - pytorch
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - aiohttp=3.7.4=py38h27cfd23_1
  - appdirs=1.4.4=pyhd3eb1b0_0
  - async-timeout=3.0.1=py38h06a4308_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - blinker=1.4=py38h06a4308_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=3.0.4=py38h06a4308_1003
  - click=8.0.1=pyhd3eb1b0_0
  - coverage=5.5=py38h27cfd23_2
  - cryptography=3.4.7=py38hd23ed53_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cython=0.29.24=py38h295c915_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.2.10=he6710b0_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.56.2=hd408876_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.3.0=h06a4308_3350
  - jpeg=9b=habf39ab_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h4ff587b_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h2531618_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.2=py38h51133e4_0
  - multidict=5.1.0=py38h27cfd23_2
  - mypy_extensions=0.4.3=py38_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numpy-base=1.21.2=py38h79a1101_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=py_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1l=h7f8727e_0
  - pathspec=0.7.0=py_0
  - pcre=8.44=he6710b0_0
  - pip=21.2.2=py38h06a4308_0
  - pyasn1=0.4.8=py_0
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycparser=2.20=py_2
  - pyjwt=2.1.0=py38h06a4308_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyqt=5.9.2=py38h05f1152_4
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - python-gnupg=0.4.7=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=py3.8_cuda10.2_cudnn7.6.5_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - regex=2021.8.3=py38h7f8727e_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - setuptools=52.0.0=py38h06a4308_0
  - sip=4.19.24=py38he6710b0_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.9.0=py38
  - torchvision=0.10.0=py38_cu102
  - typed-ast=1.4.3=py38h7f8727e_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - yarl=1.6.3=py38h27cfd23_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - stable-baselines3
    - absl-py==1.0.0
    - astroid==2.9.0
    - astunparse==1.6.3
    - cachetools==4.2.4
    - casadi==3.5.5
    - catkin-pkg==0.4.24
    - charset-normalizer==2.0.7
    - cycler==0.11.0
    - data==0.4
    - decorator==5.1.0
    - distro==1.6.0
    - docutils==0.18.1
    - empy==3.3.4
    - fonttools==4.28.1
    - funcsigs==1.0.2
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.42.0
    - h5py==2.10.0
    - idna==3.3
    - importlib-metadata==4.8.2
    - isort==5.10.1
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - latex==0.7.0
    - lazy-object-proxy==1.7.1
    - markdown==3.3.6
    - matplotlib==3.5.0
    - mccabe==0.6.1
    - mypy==0.930
    - numpy==1.21.4
    - opencv-contrib-python==4.5.5.62
    - opt-einsum==3.3.0
    - packaging==21.2
    - pandas==1.3.4
    - platformdirs==2.4.1
    - protobuf==3.19.1
    - pyasn1-modules==0.2.8
    - pycryptodome==3.12.0
    - pycryptodomex==3.12.0
    - pydocstyle==6.1.1
    - pylint==2.12.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - requests==2.26.0
    - rospkg==1.3.0
    - ruamel-yaml==0.17.17
    - ruamel-yaml-clib==0.2.6
    - scienceplots==1.0.9
    - scipy==1.4.1
    - seaborn==0.11.2
    - setuptools-scm==6.3.2
    - shutilwhich==1.1.0
    - snowballstemmer==2.2.0
    - tempdir==0.7.1
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - termcolor==1.1.0
    - tikzplotlib==0.9.16
    - tomli==1.2.2
    - torchviz==0.0.2
    - typing-extensions==4.0.1
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - wrapt==1.13.3
    - zipp==3.6.0
